# Security Configuration
app:
  jwt:
    secret: ${JWT_SECRET:myVerySecureSecretKeyThatIsAtLeast256BitsLong}
    expiration: ${JWT_EXPIRATION:86400000}
    
security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Rate limiting
rate-limit:
  enabled: ${RATE_LIMIT_ENABLED:true}
  requests-per-minute: ${RATE_LIMIT_RPM:60}
  
# Input validation
validation:
  max-string-length: 1000
  max-array-size: 1000
  sanitize-html: true