server:
  port: 8082

spring:
  application:
    name: data-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_ai_platform
    username: platform_user
    password: platform_pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices_ai_platform
      
    elasticsearch:
      repositories:
        enabled: true
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: data-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.xyzdevfoundation: DEBUG